#ifndef HOMM1_EDITOR_RANDOMMAP_H
#define HOMM1_EDITOR_RANDOMMAP_H

#include <SOURCE/mapCell.h>

struct mapStep {
    i32 x;
    i32 y;
};

enum MapStepAxis {
    MAP_STEP_X = 0,
    MAP_STEP_Y = 1,
    MAP_STEP_AXES = 2
};
typedef i32 MapStepPair[MAP_STEP_AXES];

#define MAP_GRID_CELL(grid, x, y) (*((grid) + (x) + (y) * MAP_CELL_GRID_SIZE))

enum TownPlacementConstant {
    RANDOM_MAP_CASTLE_SLOTS = 4,
    RANDOM_MAP_REGION_LIMIT = 255
};

enum TownSiteConstant {
    RANDOM_MAP_SITE_LEFT = 2,
    RANDOM_MAP_SITE_TOP = 2,
    RANDOM_MAP_SITE_RIGHT = 2,
    RANDOM_MAP_SITE_BOTTOM = 1,
    RANDOM_MAP_SITE_WIDTH = 5,
    RANDOM_MAP_SITE_HEIGHT = 4
};

enum RandomMapConstant {
    RANDOM_MAP_ATTEMPTS = 5,
    RANDOM_MAP_ANY_TERRAIN = 0xfe,
    RANDOM_MAP_FULL_PERCENT = 100,
    RANDOM_MAP_NEUTRAL_DENSITY = 50,
    RANDOM_MAP_SEED_DRIFT_MASK = 7,
    RANDOM_MAP_WEIGHT_DRIFT_MASK = 0x3f,
    RANDOM_MAP_SEED_TRIES = 200,
    RANDOM_MAP_WALK_LIMIT = 1000,
    RANDOM_MAP_SEED_LIMIT = 20,
    RANDOM_MAP_SMALL_REGION_SIZE = 15,
    RANDOM_MAP_TRIES_PER_OBJECT = 100,
    RANDOM_MAP_TRIES_PER_MINE = 1000,
    RANDOM_MAP_END_TERRAIN_SCAN = 99,
    RANDOM_MAP_UNLIMITED_STEPS = 999,
    RANDOM_MAP_NO_CHAIN_TERRAIN = -1,
    RANDOM_MAP_ANY_TREE_FAMILY = 0,
    RANDOM_MAP_OBELISK_NAME_LENGTH = 7,
    RANDOM_MAP_MINE_RESOURCE_COUNT = 5
};

enum TreasureGuard {
    TREASURE_UNGUARDED = 0,
    TREASURE_GUARD_NE = 1,
    TREASURE_GUARD_SE = 2,
    TREASURE_GUARD_SW = 3,
    TREASURE_GUARD_NW = 4,
    TREASURE_UNGUARDED_LAST = TREASURE_UNGUARDED
};

enum ChainDirection {
    CHAIN_UP_RIGHT_STEEP = 0,
    CHAIN_UP_RIGHT = 1,
    CHAIN_DOWN_RIGHT_STEEP = 2,
    CHAIN_DOWN_RIGHT = 3,
    CHAIN_DOWN_LEFT_STEEP = 4,
    CHAIN_DOWN_LEFT = 5,
    CHAIN_UP_LEFT_STEEP = 6,
    CHAIN_UP_LEFT = 7,
    CHAIN_RIGHTWARD_END = CHAIN_DOWN_LEFT_STEEP,
    CHAIN_DIRECTION_COUNT = 8
};

enum ChainTurn {
    CHAIN_TURN_CLOCKWISE = 0,
    CHAIN_TURN_COUNTERCLOCKWISE = 1,
    CHAIN_TURN_COUNT = 2
};

enum ChainTurnConstant {
    CHAIN_CLOCKWISE_STEP = 10,
    CHAIN_COUNTERCLOCKWISE_STEP = 6
};

enum ChainPiece {
    CHAIN_PIECE_STEEP_RISING = 0,
    CHAIN_PIECE_RISING = 1,
    CHAIN_PIECE_STEEP_FALLING = 2,
    CHAIN_PIECE_FALLING = 3
};

enum ChainTreeFamily {
    CHAIN_TREE_AUTUMN = 0,
    CHAIN_TREE_PINE = 1,
    CHAIN_TREE_DECIDUOUS = 2
};

void ScaleByDensity(i32* count, i32 density);

#endif
