"""Publish the generated tree as a single-commit snapshot branch.

The branch always holds exactly one root commit: master's history is not
imported, and regeneration replaces the snapshot rather than stacking on it.
Provenance lives in the commit message. The commit is assembled with Git
plumbing in a private index, so no worktree is touched; publication refuses a
branch checked out anywhere and any existing branch whose tip `homm1 clean` did
not generate. Nothing is pushed.
"""

from __future__ import annotations

import os
from pathlib import Path
import subprocess
import tempfile

from homm1.clean.project import EXECUTABLE
from homm1.clean.run import PROVENANCE, git


def publish(repo: Path, files: dict[str, bytes], commit: str, branch: str) -> str:
    """Point `branch` at a root commit holding exactly `files`; return its id."""
    git(repo, "check-ref-format", "--branch", branch)
    ref = f"refs/heads/{branch}"
    for entry in git(repo, "worktree", "list", "--porcelain").split("\n\n"):
        lines = entry.splitlines()
        if f"branch {ref}" in lines:
            raise ValueError(f"{branch}: checked out at {lines[0].removeprefix('worktree ')}; "
                             "publication never rewrites a checked-out branch")
    found = subprocess.run(["git", "-C", str(repo), "rev-parse", "--verify", "--quiet", ref],
                           capture_output=True, text=True)
    tip = found.stdout.strip() if found.returncode == 0 else None
    if tip and PROVENANCE not in git(repo, "log", "-1", "--format=%B", tip).splitlines():
        raise ValueError(f"{branch}: the branch tip was not generated by homm1 clean")

    with tempfile.TemporaryDirectory(prefix="homm1-clean-index-") as directory:
        env = dict(os.environ, GIT_INDEX_FILE=str(Path(directory) / "index"))
        entries = []
        for name, data in sorted(files.items()):
            blob = subprocess.run(["git", "-C", str(repo), "hash-object", "-w", "--stdin"],
                                  input=data, capture_output=True, check=True).stdout.decode().strip()
            mode = "100755" if name in EXECUTABLE else "100644"
            entries.append(f"{mode} {blob}\t{name}\n")
        subprocess.run(["git", "-C", str(repo), "update-index", "--index-info"],
                       input="".join(entries), text=True, env=env, check=True)
        tree = git(repo, "write-tree", env=env)

    if tip and len(git(repo, "rev-list", "--parents", "-1", tip).split()) == 1 \
            and git(repo, "rev-parse", f"{tip}^{{tree}}") == tree \
            and f"Source-Commit: {commit}" in git(repo, "log", "-1", "--format=%B", tip).splitlines():
        return tip                                    # identical regeneration: no-op
    message = (f"{branch}: generated from {commit[:12]}\n\n"
               f"{PROVENANCE}\nSource-Commit: {commit}\n")
    new_tip = git(repo, "commit-tree", tree, "-m", message)
    git(repo, "update-ref", "-m", f"homm1 clean: {branch}", ref, new_tip,
        tip or "0" * 40)
    return new_tip
