"""Gruntz graph.emit port: configure -> CL/labels -> model -> delink -> report.

Donor: b1de0e555576a215898907b8ec8ed5423368883e, scripts/gruntz/graph/emit.py.
Retains its per-edge module dependencies, include closure, generator edge,
toolchain identity files, Wine pool and restat/write-if-changed contract.
HoMM1 adapters use JSON claim fragments and per-unit sparse target objects.
Whole-data normalization and the optional executable link are deferred.
"""
from __future__ import annotations

import io
import json
from pathlib import Path
import shlex
import shutil
import sys

from homm1 import analysis, build, toolchain, publication
from homm1.core.inputs import REPO, targets
from homm1.graph import ninja_syntax
from homm1.graph.scan import Scanner

SCRIPTS = 'scripts/homm1'
MANIFEST = 'config/units.toml'
NINJA = 'build/build.ninja'


def _mods(*rel: str) -> list[str]:
    """Repo-relative module paths under scripts/homm1 that exist."""
    out = []
    for r in rel:
        p = f'{SCRIPTS}/{r}'
        if r.endswith('/'):
            out += sorted(str(q.relative_to(REPO))
                          for q in (REPO / p).glob('*.py')) if (REPO / p).is_dir() else []
        elif (REPO / p).exists():
            out.append(p)
    return out


CL_MODS = _mods('graph/cc.py', 'core/compiler.py', 'core/wine.py', 'core/profile.py', 'core/inputs.py', 'toolchain.py')
LABELS_MODS = _mods('symbols/', 'audit/common.py', 'clang_options.py', 'labels.py', 'analysis.py', 'verify.py', 'core/cpp_tokens.py', 'core/profile.py', 'core/matching.py', 'core/inputs.py', 'graph/steps.py')
MODEL_MODS = _mods('correspondence.py', 'symbols/source_symbols.py', 'model.py', 'core/manifest.py', 'core/matching.py', 'core/disasm.py', 'core/image.py', 'graph/steps.py')
DELINK_MODS = _mods('delink.py', 'core/image.py', 'core/coff.py', 'normalized_freshness.py', 'graph/steps.py')
REPORT_MODS = _mods('build.py', 'core/matching.py', 'core/coff.py', 'core/disasm.py', 'graph/steps.py')
CONFIGURE_MODS = _mods('graph/', 'build.py', 'analysis.py', 'core/profile.py', 'core/manifest.py', 'toolchain.py', 'core/inputs.py')


def write_json(path, value):
    publication.atomic_write(REPO / path, json.dumps(value, indent=2, sort_keys=True) + '\n')


def tool_identity(*names):
    identity = {}
    for name in names:
        path = shutil.which(name)
        if not path:
            raise ValueError(f'{name} is required; enter nix develop .#build')
        identity[name] = dict(path=str(Path(path).resolve()), sha256=toolchain.digest(path))
    return identity


def emit(out=None):
    config, units = build.units()
    compiler = config['build']['compiler']
    pins = toolchain.pins()[compiler]['files']
    # Like Gruntz TOOLCHAIN_ID, content-stable identities make environment
    # changes visible to Ninja without invalidating unrelated stage inputs.
    native_id = 'build/gen/toolchain/native.json'
    analysis_id = 'build/gen/toolchain/analysis.json'
    delink_id = 'build/gen/toolchain/delink.json'
    report_id = 'build/gen/toolchain/report.json'
    write_json(native_id, dict(compiler=compiler, files=pins, tools=tool_identity('wine', 'winepath', sys.executable)))
    write_json(analysis_id, dict(compiler=compiler, files=pins, tools=tool_identity('clang++', sys.executable)))
    write_json(delink_id, tool_identity('llvm-pdbutil', 'vostok-delinker', sys.executable))
    write_json(report_id, tool_identity('objdiff-cli', sys.executable))
    analysis.compilation_databases(config, units)
    scan = Scanner()
    closures = {}
    contracts = {}
    for unit in units:
        name = unit['unit']
        flags = config['flags'][unit['flags']]
        # Retain Gruntz's inactive-include over-approximation. Clang supplements
        # macro/forced includes and profile-specific include search paths.
        headers = {str(REPO / p) for p in scan.headers(unit['source'])}
        headers.update(str(p) for p in analysis.dependencies(REPO / unit['source'], compiler, flags))
        closures[name] = sorted(headers)
        contracts[name] = f'build/gen/units/{name}.json'
        write_json(contracts[name], dict(**unit, compiler=compiler, cflags=flags))
    stream = io.StringIO()
    w = ninja_syntax.Writer(stream)
    w.comment('GENERATED by homm1.graph (Gruntz graph port); edit config/units.toml.')
    w.variable('ninja_required_version', '1.11')
    w.variable('builddir', 'build')
    w.variable('py', 'PYTHONPATH=' + shlex.quote(str(REPO / 'scripts')) + ' ' + shlex.quote(sys.executable))
    w.pool('wine', 4)
    w.rule('configure', command='$py -m homm1.graph', description='configure', generator=True)
    w.build(NINJA, 'configure', implicit=[MANIFEST, 'config/toolchains.json', *CONFIGURE_MODS, *sorted(scan.scanned()),
                                        *sorted({p for paths in closures.values() for p in paths})])
    w.rule('cl', command='$py -m homm1.graph.cc --out $out --src $in --compiler $compiler --unit $unit -- $cflags',
           description='CL $unit', pool='wine', restat=True)
    w.rule('labels', command='$py -m homm1.graph.steps labels $unit', description='labels/strict $unit', restat=True)
    w.rule('model', command='$py -m homm1.graph.steps model', description='model', restat=True)
    w.rule('delink', command='$py -m homm1.graph.steps delink $unit', description='delink $unit', restat=True)
    w.rule('report', command='$py -m homm1.graph.steps report $unit', description='compare $unit', restat=True)
    fragments, bindings, reports, objects, targets_ = [], [], [], [], []
    retail = str(targets()['game'].destination.relative_to(REPO))
    tables = sorted(str(p.relative_to(REPO)) for p in (REPO / 'config/retail').glob('*') if p.is_file())
    for unit in units:
        name, source = unit['unit'], unit['source']
        obj = f'build/objdiff/base/{name}.obj'
        fragment = f'build/gen/claims/{name}.json'
        binding = f'build/gen/bindings/{name}.json'
        target = f'build/objdiff/target/{name}.obj'
        report = f'build/gen/reports/{name}.json'
        w.build(obj, 'cl', inputs=source,
                implicit=[*closures[name], *CL_MODS, contracts[name], native_id],
                variables=dict(unit=name, compiler=compiler, cflags=' '.join(shlex.quote(f) for f in config['flags'][unit['flags']]).replace('$', '$$')))
        w.build(fragment, 'labels', inputs=source,
                implicit=[*closures[name], *LABELS_MODS, contracts[name], analysis_id, 'config/cleanliness/types.toml'],
                variables={'unit': name})
        extraction = [f'build/delink/{name}/{p}' for p in ('retail.yaml', 'retail.pdb', 'code-view.exe', name + '.raw.obj', name + '.raw.obj.stamp.json')]
        w.build([target, target + '.stamp.json', *extraction], 'delink', inputs=binding,
                implicit=[retail, *DELINK_MODS, delink_id], variables={'unit': name})
        w.build(report, 'report', inputs=[obj, target, target + '.stamp.json', fragment, binding],
                implicit=['build/gen/namespace.json', retail, *tables, *REPORT_MODS, report_id, *extraction], variables={'unit': name})
        fragments.append(fragment); bindings.append(binding); reports.append(report); objects.append(obj); targets_.append(target)
    w.build([*bindings, 'build/gen/namespace.json', 'build/gen/symbol_names.csv'], 'model', inputs=fragments,
            implicit=[MANIFEST, 'config/references.toml', retail, *tables, *MODEL_MODS])
    w.build('base', 'phony', inputs=objects)
    w.build('claims', 'phony', inputs=fragments)
    w.build('target', 'phony', inputs=targets_)
    w.build('compare', 'phony', inputs=reports)
    w.build('all', 'phony', inputs=reports)
    w.default(['all'])
    # Keep the donor generator contract: its timestamp must acknowledge the
    # source/header edit even when the resulting edges are text-identical.
    # Otherwise Ninja repeatedly regenerates a manifest older than its inputs.
    (Path(out) if out else REPO / NINJA).write_text(stream.getvalue())
    return len(units)


if __name__ == '__main__':
    emit()
