#!/usr/bin/env python3
"""Turn the menu resources of a program's .rc script into a C++ table.

    python3 tools/port/menus.py --rc src/SOURCE/Heroes.rc --locale ru --out FILE

The Windows build compiles the menus into the executable's resources and
loads them with LoadMenu. The native build draws the same menus itself; this
writes them, with their text resolved in the selected language and code page,
as `kMenuResources` (see src/PORT/SOURCE/Menu.cpp for the types), and the
About box's text as `kAboutLines`. The file is
rewritten only when its contents change.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from catalog import Catalog, literal  # noqa: E402

MENU = re.compile(r"^(\w+)\s+MENU\s*$")
DIALOG = re.compile(r"^(\w+)\s+DIALOG\b")
TEXT = r'(localization::Tr\("([^"]+)"\)|"((?:[^"\\]|\\.)*)")'
POPUP = re.compile(r"^POPUP\s+" + TEXT + r"\s*$")
ITEM = re.compile(r"^MENUITEM\s+" + TEXT + r"\s*,\s*(\d+)\s*((?:,\s*\w+\s*)*)$")
CTEXT = re.compile(r"^CTEXT\s+" + TEXT + r"\s*,")

FLAG_POPUP = 1
FLAG_SEPARATOR = 2
FLAG_CHECKED = 4
FLAG_GRAYED = 8


def parse(text: str):
    """[(menu name, [(depth, flags, command, key or None, plain text)])]"""
    menus = []
    current = None
    depth = 0
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("//"):
            continue
        match = MENU.match(line)
        if match:
            current = (match.group(1).lower(), [])
            menus.append(current)
            depth = 0
            continue
        if current is None:
            continue
        if line == "BEGIN":
            depth += 1
            continue
        if line == "END":
            depth -= 1
            if depth == 0:
                current = None
            continue
        if line == "MENUITEM SEPARATOR":
            current[1].append((depth - 1, FLAG_SEPARATOR, 0, None, ""))
            continue
        match = POPUP.match(line)
        if match:
            current[1].append((depth - 1, FLAG_POPUP, 0, match.group(2), match.group(3) or ""))
            continue
        match = ITEM.match(line)
        if match:
            flags = 0
            options = {option.strip() for option in match.group(5).split(",") if option.strip()}
            if "CHECKED" in options:
                flags |= FLAG_CHECKED
            if "GRAYED" in options:
                flags |= FLAG_GRAYED
            current[1].append((depth - 1, flags, int(match.group(4)), match.group(2),
                               match.group(3) or ""))
            continue
        raise SystemExit(f"unrecognised menu line: {raw}")
    return menus


def about_lines(text: str):
    """The centred text lines of the About dialog: [(key or None, plain text)]."""
    lines = []
    inside = False
    for raw in text.splitlines():
        line = raw.strip()
        if DIALOG.match(line):
            inside = True
            continue
        if inside and line == "END":
            break
        match = CTEXT.match(line) if inside else None
        if match:
            lines.append((match.group(2), match.group(3) or ""))
    return lines


def render(menus, about, catalog, locale) -> str:
    current = catalog.locale(locale)
    lines = ["// Generated by tools/port/menus.py; do not edit.", ""]
    for name, items in menus:
        lines.append(f"static const MenuResourceItem kMenu_{name}[] = {{")
        for depth, flags, command, key, plain in items:
            value = current.messages[key] if key else plain
            text = literal(value, current.codepage)
            lines.append(f"    {{{depth}, {flags}, {command}, {text}}},")
        lines.append("};")
        lines.append("")
    lines.append("static const MenuResource kMenuResources[] = {")
    for name, items in menus:
        lines.append(f'    {{"{name}", kMenu_{name}, {len(items)}}},')
    lines.append("};")
    lines.append("")
    lines.append("// The About box's lines.")
    lines.append("static const char* const kAboutLines[] = {")
    for key, plain in about:
        value = current.messages[key] if key else plain
        lines.append(f"    {literal(value, current.codepage)},")
    lines.append("};")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--rc", type=Path, required=True)
    parser.add_argument("--locale", default="ru")
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args()
    catalog = Catalog.load(ROOT)
    script = args.rc.read_text(encoding="utf-8")
    text = render(parse(script), about_lines(script), catalog, args.locale)
    if args.out.exists() and args.out.read_text(encoding="utf-8") == text:
        return 0
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(text, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
