"""Incremental code reconstruction with strict integrity and observational scores."""
import argparse
import hashlib
import json
import os
from pathlib import Path
import re
import shlex
import shutil
import subprocess
import sys

from homm1 import toolchain, verify, analysis, model, delink, checkpoint
from homm1.core import manifest
from homm1.core.coff import CoffObject
from homm1.core.compiler import compile_source
from homm1.core.image import Image
from homm1.core.inputs import REPO, read_verified, targets
from homm1.core.matching import compare, confirm_object, retail_relocations, source_claim, target_object


def units():
    config = manifest.load()
    result = config.get('unit', [])
    seen = set()
    for unit in result:
        if set(unit) != {'unit', 'source', 'flags'} or not re.fullmatch(r'[a-z0-9_]+', unit['unit']):
            raise ValueError('units require only unit/source/flags and a simple unique unit name')
        source = (REPO / unit['source']).resolve()
        if not source.is_relative_to(REPO / 'src') or not source.is_file():
            raise ValueError('unit source must be an existing file under src/')
        if unit['unit'] in seen or unit['flags'] not in config['flags']:
            raise ValueError('duplicate unit or unknown compiler profile')
        flags = config['flags'][unit['flags']]
        if not isinstance(flags, list) or any(not isinstance(f, str) for f in flags) or '/c' not in flags:
            raise ValueError('compiler profile must be a list of flags including /c')
        seen.add(unit['unit'])
    enrolled = {u['source'] for u in result}
    physical = {str(p.relative_to(REPO)) for p in (REPO / 'src').rglob('*.cpp')}
    if enrolled != physical or len(enrolled) != len(result):
        raise ValueError(f'source enrollment differs from physical source files: {sorted(enrolled ^ physical)}')
    return config, result


def image():
    game = targets()['game']
    return Image(read_verified(game, game.destination))


def validate_claims(retail):
    claims, _ = model.resolve(retail)
    checkpoint.check_claims(claims, checkpoint.read())
    verify.check_reviews(claims)
    return claims


def compile_unit(name):
    config, entries = units()
    unit = next((u for u in entries if u['unit'] == name), None)
    if unit is None:
        raise ValueError(f'unknown unit {name}')
    compile_source(REPO / unit['source'], REPO / f'build/objdiff/base/{name}.obj',
                   config['flags'][unit['flags']], config['build']['compiler'])


def ninja_escape(value):
    return str(value).replace('$', '$$').replace(' ', '$ ').replace(':', '$:')


def configure():
    _, entries = units()
    build = REPO / 'build'
    build.mkdir(exist_ok=True)
    dependencies = sorted(p for p in (REPO / 'config').rglob('*') if p.is_file() and p.name != 'match_baseline.tsv')
    dependencies += sorted(p for p in (REPO / 'include').rglob('*') if p.is_file())
    dependencies += sorted((REPO / 'scripts/homm1').rglob('*.py'))
    command = ' '.join(shlex.quote(s) for s in [sys.executable, '-m', 'homm1.build', '--compile'])
    lines = ['# Generated by homm1 build.', 'rule cl', f'  command = {command} $unit',
             '  description = CL $unit']
    for unit in entries:
        lines += [f'build build/objdiff/base/{unit["unit"]}.obj: cl '
                  + ninja_escape(REPO / unit['source']) + ' | '
                  + ' '.join(ninja_escape(p) for p in dependencies), f'  unit = {unit["unit"]}']
    path = build / 'build.ninja'
    content = '\n'.join(lines) + '\n'
    if not path.exists() or path.read_text() != content:
        path.write_text(content)


def write_report(path, report):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(report, indent=2) + '\n')


def run(args):
    verify.check()
    retail = image()
    claims = validate_claims(retail)
    references = {c.rva: retail_relocations(retail, c) for c in claims}
    config, entries = units()
    selected = getattr(args, 'unit', None)
    if selected:
        entries = [u for u in entries if u['unit'] == selected]
        if not entries:
            raise ValueError(f'unknown unit {selected}')
    compiler = config['build']['compiler']
    toolchain.verify(compiler)
    analysis.check(config, entries)
    generation = checkpoint.fingerprint()
    configure()
    if not shutil.which('ninja') or not shutil.which('objdiff-cli'):
        raise ValueError('Ninja and objdiff-cli are required; enter nix develop .#build')
    environment = {**os.environ, 'PYTHONPATH': str(REPO / 'scripts')}
    build_targets = [f'build/objdiff/base/{u["unit"]}.obj' for u in entries]
    subprocess.run(['ninja', '-f', 'build/build.ninja', *build_targets], cwd=REPO, env=environment, check=True)
    targets = delink.generate(retail, claims, references)
    namespace = {}
    for refs in references.values():
        for ref in refs:
            name, rva = ref['symbol'], ref['target_rva']
            if name in namespace and namespace[name] != rva:
                raise ValueError(f'conflicting relocation namespace for {name}')
            namespace[name] = rva
    results = []
    objdiff_units = []
    for unit in entries:
        owned = [c for c in claims if c.unit == unit['unit']]
        base = REPO / f'build/objdiff/base/{unit["unit"]}.obj'
        target = REPO / f'build/objdiff/target/{unit["unit"]}.obj'
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(targets[unit['unit']])
        candidate = CoffObject(base.read_bytes())
        independent = CoffObject(target.read_bytes())
        confirm_object(candidate, owned)
        confirm_object(independent, owned)
        for claim in owned:
            refs = references[claim.rva]
            oracle = compare(independent, retail, claim, refs, owned, namespace)
            if not oracle['exact']:
                raise ValueError(f'delinked target fails original-retail validation: {claim.symbol}: {oracle}')
            result = compare(candidate, retail, claim, refs, owned, namespace)
            result.update(unit=unit['unit'], source=unit['source'], src_hash=claim.src_hash,
                          source_sha256=toolchain.digest(REPO / unit['source']),
                          object_sha256=toolchain.digest(base), target_object_sha256=toolchain.digest(target))
            results.append(result)
            print(f'{unit["unit"]}/{claim.symbol}: {"EXACT" if result["exact"] else "DIFF"} '
                  f'{result["matched_bytes"]}/{claim.size} bytes; '
                  f'relocations {"exact" if result["relocations_exact"] else "differ"}', flush=True)
        objdiff_units.append(dict(name=unit['unit'], target_path=str(target.relative_to(REPO / 'build/objdiff')),
                                  base_path=str(base.relative_to(REPO / 'build/objdiff'))))
        report_path = REPO / f'build/objdiff/{unit["unit"]}.diff.json'
        subprocess.run(['objdiff-cli', 'diff', '-1', str(target), '-2', str(base), '-o', str(report_path)], check=True)
        diff = json.loads(report_path.read_text())
        scores = {s['name']: float(s.get('match_percent', 0)) for s in diff['right']['symbols']
                  if s.get('kind') == 'SYMBOL_FUNCTION' and 'size' in s}
        for fn in results:
            if fn['unit'] == unit['unit']:
                if fn['symbol'] not in scores:
                    raise ValueError(f'objdiff did not measure {fn["symbol"]}')
                fn['score'] = scores[fn['symbol']]
    if not results or checkpoint.fingerprint() != generation:
        raise ValueError('empty campaign or inputs changed during the build; no checkpoint published')
    report = dict(target_sha256=hashlib.sha256(retail.data).hexdigest(), toolchain=compiler,
                  compiler_files=toolchain.pins()[compiler]['files'], flags=config['flags'],
                  scope='admitted fragments only; not whole-game coverage', functions=results,
                  fingerprint=generation, complete=not bool(selected), cleanliness=verify.check())
    report['cleanliness']['readability'] = verify.check_reviews(claims)
    if selected:
        write_report(REPO / f'build/unit-reports/{selected}.json', report)
        print('Unit report only; full checkpoint unchanged.')
    else:
        previous = checkpoint.read()
        next_rows = checkpoint.advance(previous, results)
        for fn in results:
            old = previous.get(fn['rva'])
            if old and fn['score'] < old['cur']:
                print(f'{fn["symbol"]}: score decreased {old["cur"]:.2f} -> {fn["score"]:.2f} (observational)')
        write_report(REPO / 'build/objdiff/objdiff.json', dict(units=objdiff_units))
        write_report(REPO / 'build/match-report.json', report)
        checkpoint.write(next_rows)
    return 0


def probe(args):
    retail = image()
    validate_claims(retail)
    _, entries = units()
    # Historical /Od-vs-/O2 control is established only for this callback.
    entries = [u for u in entries if u['unit'] == 'app_about']
    reports = []
    for compiler in args.ids:
        toolchain.verify(compiler)
        for optimization in ('/Od', '/O2'):
            for unit in entries:
                output = REPO / f'build/probes/{compiler}/{optimization[1:]}/{unit["unit"]}.obj'
                source = REPO / unit['source']
                compile_source(source, output, ['/nologo', '/c', optimization], compiler)
                claim = source_claim(source, retail)
                result = compare(CoffObject(output.read_bytes()), retail, claim, retail_relocations(retail, claim))
                result.update(compiler=compiler, flags=['/nologo', '/c', optimization],
                              source_sha256=toolchain.digest(source), object_sha256=toolchain.digest(output))
                reports.append(result)
                print(f'{compiler} {optimization}: {"EXACT" if result["exact"] else "DIFF"}, '
                      f'{result["compiled_size"]} bytes', flush=True)
    write_report(REPO / 'build/probes/report.json', dict(
        target_sha256=hashlib.sha256(retail.data).hexdigest(), candidates=reports,
        compiler_files={key: toolchain.pins()[key]['files'] for key in args.ids}))
    # These are compiler controls: /Od must match and /O2 must not.
    return 0 if all(r['exact'] == ('/Od' in r['flags']) for r in reports) else 1


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--compile', required=True)
    try:
        compile_unit(parser.parse_args().compile)
    except (ValueError, OSError, subprocess.SubprocessError) as exc:
        print(f'[homm1] ERROR: {exc}', file=sys.stderr)
        raise SystemExit(1)
