"""The first compile/carve/compare loop, intentionally scoped to exported fragments."""
import argparse
import csv
import hashlib
import json
import os
from pathlib import Path
import re
import shlex
import shutil
import subprocess
import sys

from homm1 import toolchain
from homm1.core import manifest
from homm1.core.coff import CoffObject
from homm1.core.compiler import compile_source
from homm1.core.image import Image
from homm1.core.inputs import REPO, read_verified, targets
from homm1.core.matching import compare, retail_relocations, source_claim, target_object


def units():
    config = manifest.load()
    result = config.get('unit', [])
    seen = set()
    for unit in result:
        if set(unit) != {'unit', 'source', 'flags'} or not re.fullmatch(r'[a-z0-9_]+', unit['unit']):
            raise ValueError('units require only unit/source/flags and a simple unique unit name')
        source = (REPO / unit['source']).resolve()
        if not source.is_relative_to(REPO / 'src') or not source.is_file():
            raise ValueError('unit source must be an existing file under src/')
        if unit['unit'] in seen or unit['flags'] not in config['flags']:
            raise ValueError('duplicate unit or unknown compiler profile')
        flags = config['flags'][unit['flags']]
        if not isinstance(flags, list) or any(not isinstance(f, str) for f in flags) or '/c' not in flags:
            raise ValueError('compiler profile must be a list of flags including /c')
        seen.add(unit['unit'])
    return config, result


def image():
    game = targets()['game']
    return Image(read_verified(game, game.destination))


def validate_claims(retail):
    admitted = manifest.check_retail(retail)
    _, entries = units()
    claims = []
    for unit in entries:
        claim = source_claim(REPO / unit['source'], retail)
        if admitted.get(claim.rva) != '':
            raise ValueError('source claim is not an admitted function body')
        if any(max(other.rva, claim.rva) < min(other.rva + other.size, claim.rva + claim.size)
               for other in claims):
            raise ValueError('overlapping reconstruction claims')
        claims.append(claim)
        retail_relocations(retail, claim)
    with (REPO / 'config/match_baseline.tsv').open() as handle:
        baseline = csv.DictReader((line for line in handle if not line.startswith('#')), delimiter='\t')
        expected = [(int(row['rva'], 0), int(row['size'], 0), row['symbol']) for row in baseline]
    actual = [(c.rva, c.size, c.symbol) for c in claims]
    if len(set(expected)) != len(expected) or any(row not in actual for row in expected):
        raise ValueError('lost or changed exact baseline claim; review against retail before updating the baseline')
    return claims


def compile_unit(name):
    config, entries = units()
    unit = next((u for u in entries if u['unit'] == name), None)
    if unit is None:
        raise ValueError(f'unknown unit {name}')
    compile_source(REPO / unit['source'], REPO / f'build/objdiff/base/{name}.obj',
                   config['flags'][unit['flags']], config['build']['compiler'])


def ninja_escape(value):
    return str(value).replace('$', '$$').replace(' ', '$ ').replace(':', '$:')


def configure():
    _, entries = units()
    build = REPO / 'build'
    build.mkdir(exist_ok=True)
    dependencies = [REPO / 'config/units.toml', REPO / 'config/toolchains.json']
    dependencies += sorted(p for p in (REPO / 'include').rglob('*') if p.is_file())
    dependencies += sorted((REPO / 'scripts/homm1').rglob('*.py'))
    command = ' '.join(shlex.quote(s) for s in [sys.executable, '-m', 'homm1.build', '--compile'])
    lines = ['# Generated by homm1 build.', 'rule cl', f'  command = {command} $unit',
             '  description = CL $unit']
    for unit in entries:
        lines += [f'build build/objdiff/base/{unit["unit"]}.obj: cl '
                  + ninja_escape(REPO / unit['source']) + ' | '
                  + ' '.join(ninja_escape(p) for p in dependencies), f'  unit = {unit["unit"]}']
    (build / 'build.ninja').write_text('\n'.join(lines) + '\n')


def write_report(path, report):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(report, indent=2) + '\n')


def run(_args):
    retail = image()
    validate_claims(retail)
    config, entries = units()
    compiler = config['build']['compiler']
    toolchain.verify(compiler)
    configure()
    if not shutil.which('ninja') or not shutil.which('objdiff-cli'):
        raise ValueError('Ninja and objdiff-cli are required; enter nix develop .#build')
    environment = {**os.environ, 'PYTHONPATH': str(REPO / 'scripts')}
    subprocess.run(['ninja', '-f', 'build/build.ninja'], cwd=REPO, env=environment, check=True)
    results = []
    objdiff_units = []
    for unit in entries:
        source = REPO / unit['source']
        claim = source_claim(source, retail)
        references = retail_relocations(retail, claim)
        base = REPO / f'build/objdiff/base/{unit["unit"]}.obj'
        target = REPO / f'build/objdiff/target/{unit["unit"]}.obj'
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(target_object(retail, claim, references))
        result = compare(CoffObject(base.read_bytes()), retail, claim, references)
        result.update(unit=unit['unit'], source=unit['source'], source_sha256=toolchain.digest(source),
                      object_sha256=toolchain.digest(base))
        results.append(result)
        objdiff_units.append(dict(name=unit['unit'], target_path=str(target.relative_to(REPO / 'build/objdiff')),
                                  base_path=str(base.relative_to(REPO / 'build/objdiff'))))
        report_path = REPO / f'build/objdiff/{unit["unit"]}.diff.json'
        subprocess.run(['objdiff-cli', 'diff', '-1', str(target), '-2', str(base), '-o', str(report_path)], check=True)
        print(f'{unit["unit"]}: {"EXACT" if result["exact"] else "DIFF"} '
              f'{result["matched_bytes"]}/{claim.size} bytes; '
              f'relocations {"exact" if result["relocations_exact"] else "differ"}', flush=True)
    write_report(REPO / 'build/objdiff/objdiff.json', dict(units=objdiff_units))
    write_report(REPO / 'build/match-report.json', dict(
        target_sha256=hashlib.sha256(retail.data).hexdigest(), toolchain=compiler,
        compiler_files=toolchain.pins()[compiler]['files'], flags=config['flags'],
        scope='admitted fragments only; not whole-game coverage', functions=results))
    return 0 if results and all(r['exact'] for r in results) else 1


def probe(args):
    retail = image()
    validate_claims(retail)
    _, entries = units()
    reports = []
    for compiler in args.ids:
        toolchain.verify(compiler)
        for optimization in ('/Od', '/O2'):
            for unit in entries:
                output = REPO / f'build/probes/{compiler}/{optimization[1:]}/{unit["unit"]}.obj'
                source = REPO / unit['source']
                compile_source(source, output, ['/nologo', '/c', optimization], compiler)
                claim = source_claim(source, retail)
                result = compare(CoffObject(output.read_bytes()), retail, claim, retail_relocations(retail, claim))
                result.update(compiler=compiler, flags=['/nologo', '/c', optimization],
                              source_sha256=toolchain.digest(source), object_sha256=toolchain.digest(output))
                reports.append(result)
                print(f'{compiler} {optimization}: {"EXACT" if result["exact"] else "DIFF"}, '
                      f'{result["compiled_size"]} bytes', flush=True)
    write_report(REPO / 'build/probes/report.json', dict(
        target_sha256=hashlib.sha256(retail.data).hexdigest(), candidates=reports,
        compiler_files={key: toolchain.pins()[key]['files'] for key in args.ids}))
    # These are compiler controls: /Od must match and /O2 must not.
    return 0 if all(r['exact'] == ('/Od' in r['flags']) for r in reports) else 1


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--compile', required=True)
    try:
        compile_unit(parser.parse_args().compile)
    except (ValueError, OSError, subprocess.SubprocessError) as exc:
        print(f'[homm1] ERROR: {exc}', file=sys.stderr)
        raise SystemExit(1)
