"""HoMM3-style generated README progress, restricted to admitted code extents."""
from collections import defaultdict

START = '<!-- homm1:campaign:start -->'
END = '<!-- homm1:campaign:end -->'


def block(report, ledger):
    functions = report['functions']
    groups = defaultdict(list)
    for fn in functions:
        groups[fn['unit']].append(fn)
    size = sum(f['retail_size'] for f in functions)
    exact = sum(f['retail_size'] for f in functions if f['exact'])
    lines = [START, '<!-- Generated by homm1 build; edit tooling, not this block. -->',
             f'**Measured campaign: {sum(f["exact"] for f in functions)}/{len(functions)} functions exact; '
             f'{exact}/{size} claimed code bytes in exact functions.**', '',
             '| Unit | Exact functions | Claimed bytes | CUR | MAX | HIST |',
             '| --- | ---: | ---: | ---: | ---: | ---: |']
    for unit, rows in sorted(groups.items()):
        total = sum(f['retail_size'] for f in rows)
        scores = [sum(ledger[f['rva']][key] * f['retail_size'] for f in rows) / total for key in ('cur', 'max', 'hist')]
        lines.append(f'| {unit} | {sum(f["exact"] for f in rows)}/{len(rows)} | {total} | ' + ' | '.join(f'{score:.2f}%' for score in scores) + ' |')
    quality = report['cleanliness']
    reviews = quality['readability']
    lines += ['', f'Cleanliness: {len(quality["findings"])} findings; {len(quality["debt_sites"])} scoped debt sites. '
              f'Source reviews: {len(reviews["reviewed"])} current, {len(reviews["pending"])} pending.', '',
              'Scores are weighted by claimed retail code size. MAX is the best for the current',
              'function source; HIST includes earlier implementations. Exactness includes resolved',
              'bytes and relocations. Located functions without measured extents are excluded.',
              'These figures are not whole-game coverage. Data matching remains deferred.', END]
    return '\n'.join(lines)


def render(readme, report, ledger):
    if readme.count(START) != 1 or readme.count(END) != 1 or readme.index(START) >= readme.index(END):
        raise ValueError('README requires exactly one ordered campaign marker pair')
    before, rest = readme.split(START)
    _, after = rest.split(END)
    return before + block(report, ledger) + after
