#ifndef HOMM1_SOURCE_ARTIFACTTYPES_H
#define HOMM1_SOURCE_ARTIFACTTYPES_H

#include <Domains.h>

// Artifact ids follow retail gArtifactNames (0x00492e60); member names use
// the short titles of gArtifactDesc, which follows it. Hero artifact slots
// mark an empty slot with -1.
H1_ENUM_BEGIN(ArtifactType)
    ARTIFACT_NONE = -1,
    ARTIFACT_ULTIMATE_BOOK = 0,
    ARTIFACT_ULTIMATE_SWORD = 1,
    ARTIFACT_ULTIMATE_CLOAK = 2,
    ARTIFACT_ULTIMATE_WAND = 3,
    ARTIFACT_ULTIMATE_LAST = ARTIFACT_ULTIMATE_WAND,
    ARTIFACT_ARCANE_NECKLACE = 4,
    ARTIFACT_CASTERS_BRACELET = 5,
    ARTIFACT_MAGES_RING = 6,
    ARTIFACT_WITCHS_BROACH = 7,
    ARTIFACT_MEDAL_OF_VALOR = 8,
    ARTIFACT_MEDAL_OF_COURAGE = 9,
    ARTIFACT_MEDAL_OF_HONOR = 10,
    ARTIFACT_MEDAL_OF_DISTINCTION = 11,
    ARTIFACT_FIZBIN_OF_MISFORTUNE = 12,
    ARTIFACT_THUNDER_MACE = 13,
    ARTIFACT_ARMORED_GAUNTLETS = 14,
    ARTIFACT_DEFENDER_HELM = 15,
    ARTIFACT_GIANT_FLAIL = 16,
    ARTIFACT_BALLISTA = 17,
    ARTIFACT_STEALTH_SHIELD = 18,
    ARTIFACT_DRAGON_SWORD = 19,
    ARTIFACT_POWER_AXE = 20,
    ARTIFACT_DIVINE_BREASTPLATE = 21,
    ARTIFACT_MINOR_SCROLL = 22,
    ARTIFACT_MAJOR_SCROLL = 23,
    ARTIFACT_SUPERIOR_SCROLL = 24,
    ARTIFACT_FOREMOST_SCROLL = 25,
    ARTIFACT_ENDLESS_SACK_OF_GOLD = 26,
    ARTIFACT_ENDLESS_BAG_OF_GOLD = 27,
    ARTIFACT_ENDLESS_PURSE_OF_GOLD = 28,
    ARTIFACT_NOMAD_BOOTS = 29,
    ARTIFACT_TRAVELER_BOOTS = 30,
    ARTIFACT_LUCKY_RABBITS_FOOT = 31,
    ARTIFACT_GOLDEN_HORSESHOE = 32,
    ARTIFACT_GAMBLERS_LUCKY_COIN = 33,
    ARTIFACT_FOUR_LEAF_CLOVER = 34,
    ARTIFACT_TRUE_COMPASS = 35,
    ARTIFACT_SAILORS_ASTROLABE = 36,
    ARTIFACT_MAGIC_BOOK = 37,
    // The regular artifacts are [REGULAR_FIRST, REGULAR_END): philAI scans
    // them from 4, and the AI/philAI hero-artifact tests accept ids below
    // REGULAR_END (everything but the magic book).
    ARTIFACT_REGULAR_FIRST = ARTIFACT_ARCANE_NECKLACE,
    ARTIFACT_REGULAR_END = ARTIFACT_MAGIC_BOOK,
    ARTIFACT_COUNT = 38
H1_ENUM_END(ArtifactType)

#endif // HOMM1_SOURCE_ARTIFACTTYPES_H
