#ifndef HOMM1_SOURCE_COMBATTYPES_H
#define HOMM1_SOURCE_COMBATTYPES_H

#include <SOURCE/armyGroup.h>

enum CombatHexDirection {
    COMBAT_DIRECTION_INVALID = -1,
    COMBAT_DIRECTION_FIRST = 0,
    COMBAT_DIRECTION_NORTHEAST = 0,
    COMBAT_DIRECTION_EAST = 1,
    COMBAT_DIRECTION_SOUTHEAST = 2,
    COMBAT_DIRECTION_SOUTHWEST = 3,
    COMBAT_DIRECTION_WEST = 4,
    COMBAT_DIRECTION_NORTHWEST = 5,
    COMBAT_DIRECTION_ADJACENT_LAST = 5,
    COMBAT_DIRECTION_WIDE_NORTH = 6,
    COMBAT_DIRECTION_WIDE_SOUTH = 7,
    COMBAT_DIRECTION_EASTERN_FIRST = 0,
    COMBAT_DIRECTION_EASTERN_LAST = 2,
    COMBAT_DIRECTION_WESTERN_FIRST = 3,
    COMBAT_DIRECTION_WESTERN_LAST = 5,
    COMBAT_DIRECTION_WIDE_FIRST = 6,
    COMBAT_DIRECTION_ADJACENT_FIRST = 0,
    COMBAT_DIRECTION_ADJACENT_COUNT = 6,
    COMBAT_DIRECTION_LAST = 7,
    COMBAT_DIRECTION_COUNT = 8
};
#define COMBAT_OPPOSITE_ADJACENT(direction)                                                        \
    (((direction) + COMBAT_DIRECTION_OPPOSITE_OFFSET) % COMBAT_DIRECTION_ADJACENT_COUNT)

enum CombatDirectionConstant {
    COMBAT_DIRECTION_OPPOSITE_OFFSET = 3
};

enum CombatPointerSectorConstant {
    COMBAT_POINTER_SECTOR_COUNT = 24,
    COMBAT_POINTER_SECTORS_PER_DIRECTION = 4,
    COMBAT_POINTER_SECTOR_FILLED = 10
};

enum CombatSide {
    COMBAT_SIDE_NONE = -1,
    COMBAT_SIDE_FIRST = 0,
    COMBAT_DEFENDER_SIDE = 0,
    COMBAT_ATTACKER_SIDE = 1,
    COMBAT_SIDE_COUNT = 2,
    COMBAT_SIDE_ANY = COMBAT_SIDE_COUNT,
    COMBAT_RESULT_DRAW = COMBAT_SIDE_NONE,
    COMBAT_RESULT_DEFENDER = COMBAT_DEFENDER_SIDE,
    COMBAT_RESULT_ATTACKER = COMBAT_ATTACKER_SIDE,
    COMBAT_RESULT_PENDING = 3
};
#define COMBAT_OPPOSING_SIDE(side) (1 - (side))
#define COMBAT_SWITCH_SIDE(side) ((side) ^= 1)

enum ArmyFacing {
    ARMY_FACING_NONE = -1,
    ARMY_FACING_RIGHT = 0,
    ARMY_FACING_LEFT = 1
};
#define ARMY_WIDE_HEX_STEP(facing) ((facing) ? -1 : 1)

enum CombatDirectionMask {
    COMBAT_DIRECTION_BIT_NORTHEAST = 0x01,
    COMBAT_DIRECTION_BIT_EAST = 0x02,
    COMBAT_DIRECTION_BIT_SOUTHEAST = 0x04,
    COMBAT_DIRECTION_BIT_SOUTHWEST = 0x08,
    COMBAT_DIRECTION_BIT_WEST = 0x10,
    COMBAT_DIRECTION_BIT_NORTHWEST = 0x20,
    COMBAT_DIRECTION_BIT_WIDE_NORTH = 0x40,
    COMBAT_DIRECTION_BIT_WIDE_SOUTH = 0x80,
    COMBAT_ALL_DIRECTIONS_BLOCKED = 0xff
};

enum CombatEffectAnimation {
    COMBAT_EFFECT_NONE = -1,
    COMBAT_EFFECT_FIREBALL = 0,
    COMBAT_EFFECT_LIGHTNING_BOLT = 1,
    COMBAT_EFFECT_TELEPORT = 2,
    COMBAT_EFFECT_CURE = 3,
    COMBAT_EFFECT_RESURRECT = 4,
    COMBAT_EFFECT_HASTE = 5,
    COMBAT_EFFECT_SLOW = 6,
    COMBAT_EFFECT_BLIND = 7,
    COMBAT_EFFECT_BLESS = 8,
    COMBAT_EFFECT_PROTECTION = 9,
    COMBAT_EFFECT_CURSE = 10,
    COMBAT_EFFECT_TURN_UNDEAD = 11,
    COMBAT_EFFECT_ANTI_MAGIC = 12,
    COMBAT_EFFECT_DISPEL_MAGIC = 13,
    COMBAT_EFFECT_BERZERKER = 14,
    COMBAT_EFFECT_ARMAGEDDON = 15,
    COMBAT_EFFECT_STORM = 16,
    COMBAT_EFFECT_METEOR_SHOWER = 17,
    COMBAT_EFFECT_PARALYZE = 18,
    COMBAT_EFFECT_GOOD_LUCK = 22,
    COMBAT_EFFECT_BAD_LUCK = 23,
    COMBAT_EFFECT_GOOD_MORALE = 24,
    COMBAT_EFFECT_BAD_MORALE = 25,
    COMBAT_EFFECT_COUNT = 26
};

enum CombatObstacleIndex {
    COMBAT_OBSTACLE_NONE = -1,
    COMBAT_OBSTACLE_FIRST_FRAME = 0,
    COMBAT_OBSTACLE_LAND_ONLY_FRAME = 2,
    COMBAT_WALL_INTACT = 8,
    COMBAT_WALL_DAMAGED = 10,
    COMBAT_WALL_INTACT_HIT = 0x40,
    COMBAT_WALL_DAMAGED_HIT = 0x41,
    COMBAT_WALL_COLLAPSING = 0x42
};

enum CombatIconSlot {
    COMBAT_ICON_GROUND = 0,
    COMBAT_ICON_TEXTBAR = 1,
    COMBAT_ICON_OBSTACLES = 2,
    COMBAT_ICON_CATAPULT = 3,
    COMBAT_ICON_TENT = 4,
    COMBAT_ICON_CASTLE = 5,
    COMBAT_ICON_CLOUD = 6,
    COMBAT_ICON_KEEP = 7,
    COMBAT_ICON_SPELLS = 8,
    COMBAT_ICON_COUNT = 9
};

enum CombatHeroHex {
    COMBAT_ATTACKER_HERO_HEX = 9,
    COMBAT_DEFENDER_HERO_HEX = 26
};

enum CombatPowEffect {
    COMBAT_POW_CLOUD = 0,
    COMBAT_POW_PHYSICAL = 1,
    COMBAT_POW_RED_FIRE = 7,
    COMBAT_POW_ELECTRIC = 8
};

enum CombatGridDimension {
    COMBAT_GRID_COLUMNS = 9,
    COMBAT_GRID_ROWS = 5,
    COMBAT_GRID_LAST_COLUMN = 8,
    COMBAT_GRID_LAST_ROW = 4,
    COMBAT_GRID_FIRST_INNER_COLUMN = 1,
    COMBAT_GRID_LAST_INNER_COLUMN = 7
};

enum CombatSpellAIGrid {
    COMBAT_SPELL_AI_ROW_END_OFFSET = 2,
    COMBAT_SPELL_AI_ROW_SKIP = 3,
    COMBAT_SPELL_AI_HEX_FIRST = 1,
    COMBAT_SPELL_AI_HEX_LAST = 0x2b
};

#endif
