#ifndef HOMM1_SOURCE_COMBATTYPES_H
#define HOMM1_SOURCE_COMBATTYPES_H

#include <Domains.h>

H1_ENUM_BEGIN(CombatHexDirection)
    COMBAT_DIRECTION_INVALID = -1,
    COMBAT_DIRECTION_NORTHEAST = 0,
    COMBAT_DIRECTION_EAST = 1,
    COMBAT_DIRECTION_SOUTHEAST = 2,
    COMBAT_DIRECTION_SOUTHWEST = 3,
    COMBAT_DIRECTION_WEST = 4,
    COMBAT_DIRECTION_NORTHWEST = 5,
    COMBAT_DIRECTION_WIDE_WEST = 6,
    COMBAT_DIRECTION_WIDE_EAST = 7,
    COMBAT_DIRECTION_OPPOSITE_OFFSET = 3,
    COMBAT_DIRECTION_ADJACENT_COUNT = 6,
    COMBAT_DIRECTION_COUNT = 8
H1_ENUM_END(CombatHexDirection)

#endif
