#ifndef HOMM1_SOURCE_CREATURETYPES_H
#define HOMM1_SOURCE_CREATURETYPES_H

#include <Domains.h>

// HoMM1 creature order: six per faction, then the four neutral types.
H1_ENUM_BEGIN(CreatureType)
    CREATURE_PEASANT = 0,
    CREATURE_ARCHER = 1,
    CREATURE_PIKEMAN = 2,
    CREATURE_SWORDSMAN = 3,
    CREATURE_CAVALRY = 4,
    CREATURE_PALADIN = 5,
    CREATURE_GOBLIN = 6,
    CREATURE_ORC = 7,
    CREATURE_WOLF = 8,
    CREATURE_OGRE = 9,
    CREATURE_TROLL = 10,
    CREATURE_CYCLOPS = 11,
    CREATURE_SPRITE = 12,
    CREATURE_DWARF = 13,
    CREATURE_ELF = 14,
    CREATURE_DRUID = 15,
    CREATURE_UNICORN = 16,
    CREATURE_PHOENIX = 17,
    CREATURE_CENTAUR = 18,
    CREATURE_GARGOYLE = 19,
    CREATURE_GRIFFIN = 20,
    CREATURE_MINOTAUR = 21,
    CREATURE_HYDRA = 22,
    CREATURE_DRAGON = 23,
    CREATURE_ROGUE = 24,
    CREATURE_NOMAD = 25,
    CREATURE_GHOST = 26,
    CREATURE_GENIE = 27,
    CREATURE_COUNT = 28
H1_ENUM_END(CreatureType)

#endif
