#ifndef HOMM1_SOURCE_CURSORTYPES_H
#define HOMM1_SOURCE_CURSORTYPES_H

#include <Domains.h>

H1_ENUM_BEGIN(MapDirection)
    MAP_DIRECTION_NORTH = 0,
    MAP_DIRECTION_NORTH_EAST = 1,
    MAP_DIRECTION_EAST = 2,
    MAP_DIRECTION_SOUTH_EAST = 3,
    MAP_DIRECTION_SOUTH = 4,
    MAP_DIRECTION_SOUTH_WEST = 5,
    MAP_DIRECTION_WEST = 6,
    MAP_DIRECTION_NORTH_WEST = 7
H1_ENUM_END(MapDirection)

H1_ENUM_BEGIN(CursorFrameConstant)
    CURSOR_FRAMES_PER_DIRECTION = 9,
    CURSOR_BOAT_BASE_FRAME_5 = 0x9b,
    CURSOR_BOAT_BASE_FRAME_6 = 0x92,
    CURSOR_BOAT_BASE_FRAME_7 = 0x89
H1_ENUM_END(CursorFrameConstant)

#endif
