#ifndef HOMM1_SOURCE_CURSORTYPES_H
#define HOMM1_SOURCE_CURSORTYPES_H

enum MapDirection {
    MAP_DIRECTION_NONE = -1,
    MAP_DIRECTION_NORTH = 0,
    MAP_DIRECTION_FIRST = MAP_DIRECTION_NORTH,
    MAP_DIRECTION_NORTH_EAST = 1,
    MAP_DIRECTION_EAST = 2,
    MAP_DIRECTION_SOUTH_EAST = 3,
    MAP_DIRECTION_SOUTH = 4,
    MAP_DIRECTION_SOUTH_WEST = 5,
    MAP_DIRECTION_WEST = 6,
    MAP_DIRECTION_NORTH_WEST = 7,
    MAP_DIRECTION_COUNT = 8,
    MAP_DIRECTION_UNMIRRORED_LAST = MAP_DIRECTION_SOUTH
};

enum MapDirectionMask {
    MAP_DIRECTION_NORTH_MASK = 0x83,
    MAP_DIRECTION_SOUTH_MASK = 0x38
};

enum WalkSpeed {
    WALK_SPEED_WALK = 0,
    WALK_SPEED_FIRST = WALK_SPEED_WALK,
    WALK_SPEED_TROT = 1,
    WALK_SPEED_CANTER = 2,
    WALK_SPEED_GALLOP = 3,
    WALK_SPEED_JUMP = 4,
    WALK_SPEED_COUNT = 5
};
#define WALK_SPEED_WRAP(speed) ((speed) %= WALK_SPEED_COUNT)

enum MapDirectionConstant {
    MAP_DIRECTION_OPPOSITE_OFFSET = 4,
    MAP_DIRECTION_INDEX_MASK = 7,
    MAP_DIRECTION_DIAGONAL_BIT = 1
};

inline i32 OppositeMapDirection(i32 direction) {
    return (direction + MAP_DIRECTION_OPPOSITE_OFFSET) & MAP_DIRECTION_INDEX_MASK;
}

enum CursorFrameConstant {
    CURSOR_FRAMES_PER_DIRECTION = 9,
    CURSOR_BOAT_BASE_FRAME_5 = 0x9b,
    CURSOR_BOAT_BASE_FRAME_6 = 0x92,
    CURSOR_BOAT_BASE_FRAME_7 = 0x89
};

enum AdventurePointerFrame {
    ADVENTURE_POINTER_DEFAULT = 0,
    ADVENTURE_POINTER_WAIT = 1,
    ADVENTURE_POINTER_HERO = 2,
    ADVENTURE_POINTER_TOWN = 3,
    ADVENTURE_POINTER_MOVE = 4,
    ADVENTURE_POINTER_ATTACK = 5,
    ADVENTURE_POINTER_SAIL = 6,
    ADVENTURE_POINTER_DISEMBARK = 7,
    ADVENTURE_POINTER_SELECT_HERO = 8,
    ADVENTURE_POINTER_ACTION = 9,
    ADVENTURE_POINTER_WATER_ACTION = 28
};

enum AdventurePointerConstant {
    ADVENTURE_POINTER_DAY_STRIDE = 6,
    ADVENTURE_POINTER_DAY_LAST = 3
};

#endif
