#ifndef HOMM1_SOURCE_DIALOGTYPES_H
#define HOMM1_SOURCE_DIALOGTYPES_H

#include <Domains.h>

H1_ENUM_BEGIN(NormalDialogWidgetRange)
    NORMAL_DIALOG_FOREGROUND_WIDGET_LIMIT = 0x9000,
    NORMAL_DIALOG_BACKGROUND_WIDGET_LAST_ID = -256
H1_ENUM_END(NormalDialogWidgetRange)

H1_ENUM_BEGIN(NormalDialogResult)
    NORMAL_DIALOG_CONFIRM = 0x7805,
    NORMAL_DIALOG_CANCEL = 0x7806
H1_ENUM_END(NormalDialogResult)

// clang-format off
// HoMM1 NormalDialog's resource slot kinds (frames of resource.icn first).
H1_ENUM_BEGIN(NormalDialogResourceType)
    NORMAL_DIALOG_NO_RESOURCE = -1,
    NORMAL_DIALOG_RESOURCE_GOLD = 6,
    NORMAL_DIALOG_RESOURCE_LAST = NORMAL_DIALOG_RESOURCE_GOLD,
    NORMAL_DIALOG_ARTIFACT = 7,
    NORMAL_DIALOG_SPELL = 8,
    NORMAL_DIALOG_CREST = 9,
    NORMAL_DIALOG_LUCK_BONUS = 10,
    NORMAL_DIALOG_LUCK_PENALTY = 11,
    NORMAL_DIALOG_MORALE_BONUS = 12,
    NORMAL_DIALOG_MORALE_PENALTY = 13,
    NORMAL_DIALOG_EXPERIENCE = 14,
    NORMAL_DIALOG_EXPMRL_FIRST = NORMAL_DIALOG_LUCK_BONUS,
    NORMAL_DIALOG_HERO = 15
H1_ENUM_END(NormalDialogResourceType)

// NormalDialog's dialogType argument: which of evntwin*.bin's buttons stay.
H1_ENUM_BEGIN(NormalDialogType)
    NORMAL_DIALOG_TYPE_OK = 1,
    NORMAL_DIALOG_TYPE_YES_NO = 2,
    NORMAL_DIALOG_TYPE_NO_BUTTONS = 3,
    NORMAL_DIALOG_TYPE_QUICK_VIEW = 4,
    NORMAL_DIALOG_TYPE_WAIT_OK = 5,
    NORMAL_DIALOG_TYPE_WAIT_CANCEL = 6
H1_ENUM_END(NormalDialogType)

H1_ENUM_BEGIN(NormalDialogButton)
    NORMAL_DIALOG_BUTTON_OK = 0x7801,
    NORMAL_DIALOG_BUTTON_CANCEL = 0x7802,
    NORMAL_DIALOG_BUTTON_YES = 0x7805,
    NORMAL_DIALOG_BUTTON_NO = 0x7806
H1_ENUM_END(NormalDialogButton)

H1_ENUM_BEGIN(NormalDialogLayout)
    NORMAL_DIALOG_RESOURCE_COUNT = 2,
    NORMAL_DIALOG_SHOW_OR_TEXT = 1,
    NORMAL_DIALOG_NO_VALUE = -1,
    NORMAL_DIALOG_TEXT_LENGTH = 40,
    NORMAL_DIALOG_FILENAME_LENGTH = 16,
    NORMAL_DIALOG_TEXT_LINE_WIDTH = 240,
    NORMAL_DIALOG_TEXT_LINE_HEIGHT = 16,
    NORMAL_DIALOG_BUTTON_AREA_HEIGHT = 39,
    NORMAL_DIALOG_RESOURCE_LABEL_HEIGHT = 12,
    NORMAL_DIALOG_WINDOW_ROW_HEIGHT = 45,
    NORMAL_DIALOG_MAX_ROWS = 7,
    NORMAL_DIALOG_WINDOW_WIDTH = 286,
    NORMAL_DIALOG_WINDOW_BASE_HEIGHT = 129,
    NORMAL_DIALOG_ADVENTURE_X = 97,
    NORMAL_DIALOG_MAX_TOP = 28,
    NORMAL_DIALOG_RESOURCE_BOTTOM_INSET = 27,
    NORMAL_DIALOG_TEXT_WIDGET_FIRST_ID = 100,
    NORMAL_DIALOG_TEXT_WIDGET_ID = 1,
    NORMAL_DIALOG_BUTTON_FLAGS = 6
H1_ENUM_END(NormalDialogLayout)
// clang-format on

#endif // HOMM1_SOURCE_DIALOGTYPES_H
