#ifndef HOMM1_SOURCE_DIALOGTYPES_H
#define HOMM1_SOURCE_DIALOGTYPES_H

enum NormalDialogWidgetRange {
    NORMAL_DIALOG_FOREGROUND_WIDGET_LIMIT = 0x9000,
    NORMAL_DIALOG_BACKGROUND_WIDGET_LAST_ID = -256
};

enum NormalDialogResult {
    NORMAL_DIALOG_CONFIRM = 0x7805,
    NORMAL_DIALOG_CANCEL = 0x7806
};

enum NormalDialogResourceType {
    NORMAL_DIALOG_NO_RESOURCE = -1,
    NORMAL_DIALOG_RESOURCE_WOOD = 0,
    NORMAL_DIALOG_RESOURCE_MERCURY = 1,
    NORMAL_DIALOG_RESOURCE_ORE = 2,
    NORMAL_DIALOG_RESOURCE_SULFUR = 3,
    NORMAL_DIALOG_RESOURCE_CRYSTAL = 4,
    NORMAL_DIALOG_RESOURCE_GEMS = 5,
    NORMAL_DIALOG_RESOURCE_GOLD = 6,
    NORMAL_DIALOG_RESOURCE_LAST = NORMAL_DIALOG_RESOURCE_GOLD,
    NORMAL_DIALOG_ARTIFACT = 7,
    NORMAL_DIALOG_SPELL = 8,
    NORMAL_DIALOG_CREST = 9,
    NORMAL_DIALOG_LUCK_BONUS = 10,
    NORMAL_DIALOG_LUCK_PENALTY = 11,
    NORMAL_DIALOG_MORALE_BONUS = 12,
    NORMAL_DIALOG_MORALE_PENALTY = 13,
    NORMAL_DIALOG_EXPERIENCE = 14,
    NORMAL_DIALOG_EXPMRL_FIRST = NORMAL_DIALOG_LUCK_BONUS,
    NORMAL_DIALOG_HERO = 15
};

enum NormalDialogType {
    NORMAL_DIALOG_TYPE_OK = 1,
    NORMAL_DIALOG_TYPE_YES_NO = 2,
    NORMAL_DIALOG_TYPE_NO_BUTTONS = 3,
    NORMAL_DIALOG_TYPE_QUICK_VIEW = 4,
    NORMAL_DIALOG_TYPE_WAIT_OK = 5,
    NORMAL_DIALOG_TYPE_WAIT_CANCEL = 6
};

enum NormalDialogOrText {
    NORMAL_DIALOG_NO_OR_TEXT = -1,
    NORMAL_DIALOG_SHOW_OR_TEXT = 1
};

enum NormalDialogButton {
    NORMAL_DIALOG_BUTTON_OK = 0x7801,
    NORMAL_DIALOG_BUTTON_CANCEL = 0x7802,
    NORMAL_DIALOG_BUTTON_YES = 0x7805,
    NORMAL_DIALOG_BUTTON_NO = 0x7806
};

enum NormalDialogLayout {
    NORMAL_DIALOG_RESOURCE_COUNT = 2,
    NORMAL_DIALOG_NO_VALUE = -1,
    NORMAL_DIALOG_TEXT_LENGTH = 40,
    NORMAL_DIALOG_FILENAME_LENGTH = 16,
    NORMAL_DIALOG_TEXT_LINE_WIDTH = 240,
    NORMAL_DIALOG_TEXT_LINE_HEIGHT = 16,
    NORMAL_DIALOG_BUTTON_AREA_HEIGHT = 39,
    NORMAL_DIALOG_RESOURCE_LABEL_HEIGHT = 12,
    NORMAL_DIALOG_WINDOW_ROW_HEIGHT = 45,
    NORMAL_DIALOG_MAX_ROWS = 7,
    NORMAL_DIALOG_WINDOW_WIDTH = 286,
    NORMAL_DIALOG_WINDOW_BASE_HEIGHT = 129,
    NORMAL_DIALOG_ADVENTURE_X = 97,
    NORMAL_DIALOG_MAX_TOP = 28,
    NORMAL_DIALOG_RESOURCE_BOTTOM_INSET = 27,
    NORMAL_DIALOG_TEXT_WIDGET_FIRST_ID = 100,
    NORMAL_DIALOG_TEXT_WIDGET_ID = 1,
    NORMAL_DIALOG_BUTTON_FLAGS = 6
};

enum DialogWaitType {
    DIALOG_WAIT_OTHER_PLAYER = 0,
    DIALOG_WAIT_NETBIOS_GUEST = 1,
    DIALOG_WAIT_NETBIOS_HOST = 2,
    DIALOG_WAIT_NETBIOS_INIT_GUEST = 3,
    DIALOG_WAIT_NETBIOS_INIT_HOST = 4,
    DIALOG_WAIT_MODEM_COMMAND = 5,
    DIALOG_WAIT_MODEM_RESPONSE = 6,
    DIALOG_WAIT_DIRECT_CONNECT = 7
};

#endif
