#ifndef HOMM1_SOURCE_EVENTS_H
#define HOMM1_SOURCE_EVENTS_H

#include <SOURCE/armyGroup.h>
#include <SOURCE/combatTypes.h>
#include <SOURCE/hero.h>
#include <SOURCE/REMOTE.h>
#include <SOURCE/resourceTypes.h>
#include <SOURCE/town.h>

enum MapObjectEncodingConstant {
    MAP_EVENT_DATA_EMPTY = 0,
    MAP_EVENT_DATA_AVAILABLE = 1,
    CAMPFIRE_RESOURCE_MASK = 0xf,
    CAMPFIRE_AMOUNT_SHIFT = 4,
    SKELETON_EMPTY = 1,
    SKELETON_ARTIFACT = 2,
    ARTIFACT_EVENT_MODE_PICKUP = 1,
    ARTIFACT_EVENT_MODE_GUARDED = 2,
    ARTIFACT_EVENT_MODE_GOLD = 3,
    DAEMON_CAVE_EMPTY = 1,
    DAEMON_REWARD_EXPERIENCE = 2,
    DAEMON_REWARD_ARTIFACT = 3,
    DAEMON_REWARD_EXPERIENCE_GOLD = 4,
    DAEMON_REWARD_RANSOM = 5,
    GHOST_SITE_EMPTY = 1,
    GHOST_SITE_SMALL = 2,
    GHOST_SITE_MEDIUM = 3,
    GHOST_SITE_LARGE = 4,
    GHOST_SITE_HUGE = 5,
    WINDMILL_RESOURCE_LAST = 6,
    MAP_EVENT_SPELL_OFFSET = 1,
    WINDMILL_EMPTY = 99,
    RESOURCE_PILE_OBJECT_BASE = 0x3d,
    MONSTER_WILLING_FLAG = 0x80,
    MONSTER_COUNT_MASK = 0x7f
};

enum MapEventRewardConstant {
    MINE_GOLD_INCOME = 1000,
    MINE_ORE_INCOME = 2,
    MINE_RARE_INCOME = 1,
    SAWMILL_WOOD_INCOME = 2,
    ALCHEMIST_MERCURY_INCOME = 1,
    DRAGON_CITY_GOLD_INCOME = 1000,
    DRAGON_CITY_DRAGON_COUNT = 5,
    DRAGON_CITY_CAMPAIGN_DRAGON_COUNT = 20,
    CHEST_GOLD_MULTIPLIER = 500,
    CHEST_EXPERIENCE_MULTIPLIER = 500,
    CHEST_EXPERIENCE_LEVEL_OFFSET = 1,
    SKELETON_GOLD = 1000,
    CAMPFIRE_GOLD_MULTIPLIER = 100,
    GAZEBO_EXPERIENCE = 1000,
    WATERWHEEL_GOLD_MULTIPLIER = 500,
    RESOURCE_PILE_GOLD_MULTIPLIER = 100,
    WINDMILL_RESOURCE_AMOUNT = 2,
    TEMPLE_MORALE_BONUS = 2,
    ARTIFACT_EVENT_GUARD_ROGUE_COUNT = 50,
    ARTIFACT_EVENT_GOLD_COST = 2000,
    EVENT_RANDOM_ARTIFACT_GOLD = 1000,
    DAEMON_EXPERIENCE = 1000,
    DAEMON_GOLD = 2500,
    GHOST_SMALL_COUNT = 10,
    GHOST_SMALL_GOLD = 1000,
    GHOST_MEDIUM_COUNT = 15,
    GHOST_MEDIUM_GOLD = 2000,
    GHOST_LARGE_COUNT = 25,
    GHOST_LARGE_GOLD = 5000,
    GHOST_HUGE_COUNT = 50,
    GHOST_HUGE_GOLD = 2000,
    // The Paladin stronghold on a megalith: paladins guard it; beaten, the
    // ghosts they kept join the hero, or wait there until he has room.
    STRONGHOLD_GUARDED = 0,
    STRONGHOLD_ABANDONED = 1,
    STRONGHOLD_GHOSTS_WAITING = 2,
    STRONGHOLD_PALADIN_COUNT = 10,
    STRONGHOLD_GHOST_COUNT = 10
};

enum EventFizzleType {
    EVENT_FIZZLE_HERO_LOSS = 0,
    EVENT_FIZZLE_PICKUP = 1
};

enum EventArtifactStat {
    EVENT_ARTIFACT_GIVE = 0,
    EVENT_ARTIFACT_TAKE = 1
};

enum MapEventDisplayConstant {
    COAST_FIZZLE_X = 0xc0,
    COAST_FIZZLE_Y = 0xc0,
    COAST_FIZZLE_WIDTH = 0x60,
    COAST_FIZZLE_HEIGHT = 0x60,
    EVENT_FIZZLE_X = 180,
    EVENT_FIZZLE_Y = 172,
    EVENT_FIZZLE_WIDTH = 120,
    EVENT_FIZZLE_HEIGHT = 120,
    EVENT_FIZZLE_STEPS = 65,
    STONE_LITHS_MIN_DISTANCE = 1,
    WHIRLPOOL_MIN_DISTANCE = 3,
    EVENT_WHIRLPOOL_TRIGGER_ROLL = 1,
    EVENT_WHIRLPOOL_TRIGGER_MAX = 3,
    EVENT_WHIRLPOOL_ARMY_VALUE_LIMIT = 99999999,
    EVENT_WHIRLPOOL_NO_SLOT = -1,
    EVENT_TEXT_BUFFER_SIZE = 500
};

enum CombatFlowConstant {
    COMBAT_NETWORK_POLL_X = 30,
    COMBAT_NETWORK_POLL_Y = 30,
    COMBAT_NETWORK_POLL_WIDTH = 4,
    COMBAT_NETWORK_POLL_HEIGHT = 4,
    COMBAT_LOW_MEMORY_LIMIT = 600,
    COMBAT_HIGH_MEMORY_LIMIT = 1450,
    COMBAT_RANDOM_SEED_NEW = -1,
    COMBAT_RANDOM_SEED_MAX = 1000
};

extern b8 gEventMusicPlaying;

enum MapEventTextId {
    EVENT_TEXT_CUSTOM = -1,
    EVENT_TEXT_ALCHEMIST_CAPTURED = 0,
    EVENT_TEXT_FIRST = EVENT_TEXT_ALCHEMIST_CAPTURED,
    EVENT_TEXT_SIGNPOST = 1,
    EVENT_TEXT_BUOY_VISITED = 2,
    EVENT_TEXT_BUOY_REWARD = 3,
    EVENT_TEXT_DAEMON_CAVE_EMPTY = 4,
    EVENT_TEXT_DAEMON_CAVE_EXPERIENCE = 5,
    EVENT_TEXT_DAEMON_CAVE_ARTIFACT = 6,
    EVENT_TEXT_DAEMON_CAVE_GOLD = 7,
    EVENT_TEXT_DAEMON_CAVE_RANSOM = 8,
    EVENT_TEXT_DAEMON_CAVE_DEATH = 9,
    EVENT_TEXT_DAEMON_CAVE_PROMPT = 10,
    EVENT_TEXT_TREASURE_CHEST = 11,
    EVENT_TEXT_FAERIE_RING_VISITED = 12,
    EVENT_TEXT_FAERIE_RING_REWARD = 13,
    EVENT_TEXT_CAMPFIRE = 14,
    EVENT_TEXT_FOUNTAIN_VISITED = 15,
    EVENT_TEXT_FOUNTAIN_REWARD = 16,
    EVENT_TEXT_GAZEBO_VISITED = 17,
    EVENT_TEXT_GAZEBO_REWARD = 18,
    EVENT_TEXT_GENIE_LAMP = 19,
    EVENT_TEXT_GRAVEYARD_PROMPT = 20,
    EVENT_TEXT_GRAVEYARD_EMPTY = 21,
    EVENT_TEXT_GRAVEYARD_REWARD = 22,
    EVENT_TEXT_HOUSE_RECRUIT = 23,
    EVENT_TEXT_HOUSE_RANKS_FULL = 24,
    EVENT_TEXT_HOUSE_EMPTY = 25,
    EVENT_TEXT_DRAGON_CITY_PROMPT = 38,
    EVENT_TEXT_DRAGON_CITY_CONQUERED = 39,
    EVENT_TEXT_LIGHTHOUSE_CAPTURED = 40,
    EVENT_TEXT_WATERWHEEL_EMPTY = 41,
    EVENT_TEXT_MINE_CAPTURED_BASE = 41,
    EVENT_TEXT_WATERWHEEL_REWARD = 42,
    EVENT_TEXT_FOLLOWERS = 48,
    EVENT_TEXT_MONSTER_REFUSAL = 49,
    EVENT_TEXT_OBELISK_REWARD = 50,
    EVENT_TEXT_OBELISK_VISITED = 51,
    EVENT_TEXT_OASIS_VISITED = 52,
    EVENT_TEXT_OASIS_REWARD = 53,
    EVENT_TEXT_RESOURCE_PICKUP = 54,
    EVENT_TEXT_SAWMILL_CAPTURED = 55,
    EVENT_TEXT_RANKING_SHRINE = 56,
    EVENT_TEXT_SPELL_SHRINE = 57,
    EVENT_TEXT_SHIPWRECK_PROMPT = 58,
    EVENT_TEXT_SHIPWRECK_EMPTY = 59,
    EVENT_TEXT_SHIPWRECK_REWARD = 60,
    EVENT_TEXT_STATUE_REWARD = 61,
    EVENT_TEXT_STATUE_VISITED = 62,
    EVENT_TEXT_DESERT_TENT_EMPTY = 63,
    EVENT_TEXT_DESERT_TENT_RECRUIT = 64,
    EVENT_TEXT_WAGON_EMPTY = 65,
    EVENT_TEXT_WAGON_RECRUIT = 66,
    EVENT_TEXT_WINDMILL_EMPTY = 68,
    EVENT_TEXT_WINDMILL_REWARD = 69,
    EVENT_TEXT_ARTIFACT_GUARDED = 70,
    EVENT_TEXT_LEPRECHAUN_OFFER = 71,
    EVENT_TEXT_LEPRECHAUN_REFUSAL = 72,
    EVENT_TEXT_LEPRECHAUN_NO_GOLD = 73,
    EVENT_TEXT_ARTIFACT_RECOVERED = 74,
    EVENT_TEXT_SKELETON_EMPTY = 75,
    EVENT_TEXT_WINDOW_END = 76,
    EVENT_TEXT_SKELETON_ARTIFACT = 76,
    EVENT_TEXT_COUNT = 77
};
extern char* gEventText[EVENT_TEXT_COUNT];

enum HouseEventConstant {
    EVENT_TEXT_HOUSE_STRIDE = 3,
    EVENT_HOUSE_COUNT = 5
};

#define EVENT_TEXT_HOUSE(house, row) ((house) * EVENT_TEXT_HOUSE_STRIDE + (row))
#define EVENT_TEXT_MINE_CAPTURED(resource) ((resource) + EVENT_TEXT_MINE_CAPTURED_BASE)

enum CombatRemoteConstant {
    COMBAT_REMOTE_FRAGMENT_COMBAT = 0,
    COMBAT_REMOTE_FRAGMENT_FIRST_HERO = 1,
    COMBAT_REMOTE_FRAGMENT_SECOND_HERO = 2,
    COMBAT_REMOTE_BUFFER_SIZE = 0xff
};

// The battle a network peer is to fight or has fought (fragment 0 of
// REMOTE_COMMAND_HERO_TOWN_DATA); the heroes follow as fragments 1 and 2.
// remoteRecords.h encodes it in the original's packed layout.
struct combatRemoteData {
    i8 fragment;
    i8 x;
    i8 y;
    b8 hasFirstHero;
    b8 hasTown;
    b8 hasSecondHero;
    i8 setupCombatX;
    i8 setupCombatY;
    i32 randomSeed;
    i8 combatResult;
    b8 retreatWin;
    b8 combatSurrender;
    i8 firstOwner;
    i32 firstGold;
    i8 secondOwner;
    i32 secondGold;
    armyGroup firstArmy;
    armyGroup secondArmy;
    town combatTown;
};

#endif
