#ifndef HOMM1_SOURCE_HIGHSCORE_RUNTIME_H
#define HOMM1_SOURCE_HIGHSCORE_RUNTIME_H

#include <Domains.h>

H1_ENUM_BEGIN(HighScoreRuntimeConstant)
    HIGH_SCORE_FADE_IN = 0,
    HIGH_SCORE_ANIMATION_DELAY = 120,
    HIGH_SCORE_TIMER_SLOT = 0,
    HIGH_SCORE_MANAGER_OPEN_OK = 0,
    HIGH_SCORE_ANIMATION_FRAME_DIVISOR = 3,
    HIGH_SCORE_FIRST_MONSTER_WIDGET = 201,
    HIGH_SCORE_MONSTER_FRAME_STRIDE = 7,
    HIGH_SCORE_ANIMATED_WIDGET_FIRST = 200,
    HIGH_SCORE_ANIMATED_WIDGET_LAST = 210,
    HIGH_SCORE_UPDATE_X = 538,
    HIGH_SCORE_UPDATE_Y = 54,
    HIGH_SCORE_UPDATE_WIDTH = 50,
    HIGH_SCORE_UPDATE_HEIGHT = 400,
    HIGH_SCORE_STANDARD_BUTTON = 100,
    HIGH_SCORE_CAMPAIGN_BUTTON = 147,
    HIGH_SCORE_CLOSE_BUTTON = 0x7800
H1_ENUM_END(HighScoreRuntimeConstant)

extern long glTimers[];
extern void *hmnuDflt;

#endif
