#ifndef HOMM1_SOURCE_RESOURCETYPES_H
#define HOMM1_SOURCE_RESOURCETYPES_H

enum ResourceType {
    RESOURCE_NONE = -1,
    RESOURCE_WOOD = 0,
    RESOURCE_FIRST = RESOURCE_WOOD,
    RESOURCE_MERCURY = 1,
    RESOURCE_ORE = 2,
    RESOURCE_SULFUR = 3,
    RESOURCE_CRYSTAL = 4,
    RESOURCE_GEMS = 5,
    RESOURCE_NON_GOLD_END = 6,
    RESOURCE_GOLD = 6,
    RESOURCE_LAST = RESOURCE_GOLD,
    RESOURCE_COUNT = 7
};

#endif
