#ifndef HOMM1_SOURCE_RESOURCETYPES_H
#define HOMM1_SOURCE_RESOURCETYPES_H

#include <Domains.h>

H1_ENUM_BEGIN(ResourceType)
    RESOURCE_WOOD = 0,
    RESOURCE_MERCURY = 1,
    RESOURCE_ORE = 2,
    RESOURCE_SULFUR = 3,
    RESOURCE_CRYSTAL = 4,
    RESOURCE_GEMS = 5,
    RESOURCE_GOLD = 6,
    RESOURCE_LAST = RESOURCE_GOLD,
    RESOURCE_COUNT = 7
H1_ENUM_END(ResourceType)

#endif
