#ifndef HOMM1_SOURCE_TERRAINTYPES_H
#define HOMM1_SOURCE_TERRAINTYPES_H

enum TerrainType {
    TERRAIN_INVALID = -1,
    TERRAIN_WATER = 0,
    TERRAIN_GRASS = 1,
    TERRAIN_SNOW = 2,
    TERRAIN_SWAMP = 3,
    TERRAIN_LAVA = 4,
    TERRAIN_DESERT = 5,
    TERRAIN_DIRT = 6,
    TERRAIN_LAST = TERRAIN_DIRT,
    TERRAIN_WATER_LAST = TERRAIN_WATER,
    TERRAIN_COUNT = 7
};

#define TERRAIN_IS_LAND(t) (t)

#endif
