#ifndef HOMM1_SOURCE_VIEW_H
#define HOMM1_SOURCE_VIEW_H

#include <BASE/message.h>

struct tag_message;

i16 HandleViewGeneral(struct tag_message& message);

enum ViewGeneralControl {
    GENERAL_CONTROL_NONE = 0,
    GENERAL_NAME_WIDGET = 1,
    GENERAL_PORTRAIT_WIDGET = 2,
    GENERAL_COLOR_WIDGET = 3,
    GENERAL_STATS_WIDGET = 4,
    GENERAL_CONTROL_SEVEN = 7,
    GENERAL_CONTROL_EIGHT = 8,
    GENERAL_CONTROL_NINE = 9,
    GENERAL_CAST_SPELL = 10,
    GENERAL_RETREAT = 11,
    GENERAL_SURRENDER = 12,
    GENERAL_CONTROL_THIRTEEN = 13,
    GENERAL_CONTROL_FOURTEEN = 14
};

enum ViewGeneralHoverHelp {
    GENERAL_HOVER_HELP_CAST_SPELL = 1,
    GENERAL_HOVER_HELP_RETREAT = 2,
    GENERAL_HOVER_HELP_SURRENDER = 3,
    GENERAL_HOVER_HELP_CLOSE = 4,
    GENERAL_HOVER_HELP_HERO = 5,
    GENERAL_HOVER_HELP_COUNT = 6
};

#endif
