#ifndef HOMM1_SOURCE_WINGRAPH_H
#define HOMM1_SOURCE_WINGRAPH_H

#include <BASE/display.h>

enum WingraphPaintConstant {
    WINGRAPH_PAINT_ALIGN_MASK = 0xfffc,
    WINGRAPH_SYSTEM_PALETTE_SIZE = 10,
    WINGRAPH_SYSTEM_PALETTE_END = WINGRAPH_SYSTEM_PALETTE_SIZE,
    WINGRAPH_MUTABLE_PALETTE_END = PALETTE_COLOR_COUNT - WINGRAPH_SYSTEM_PALETTE_SIZE,
    WINGRAPH_LIMITED_COMBAT_HEIGHT = 458,
    WINGRAPH_COLOR_DEPTH = 8,
    WINGRAPH_PALETTE_VALUE_SHIFT = 2,
    WINGRAPH_SCROLL_MARGIN = 16,
    WINGRAPH_SCROLL_SIZE = LOGICAL_SCREEN_HEIGHT - WINGRAPH_SCROLL_MARGIN * 2,
    WINGRAPH_PAINT_TIMEOUT = 10000
};

enum WingraphGraphicsType {
    WINGRAPH_GRAPHICS_WING = 1,
    WINGRAPH_GRAPHICS_DIRECT_DRAW = 2
};

enum DirectDrawReportCode {
    DDSD_REPORT_NONE = 0,
    DDSD_REPORT_GENERIC = 1,
    DDSD_REPORT_INVALIDCLIPLIST = 2,
    DDSD_REPORT_INVALIDOBJECT = 3,
    DDSD_REPORT_INVALIDPARAMS = 4,
    DDSD_REPORT_INVALIDRECT = 5,
    DDSD_REPORT_NOALPHAHW = 6,
    DDSD_REPORT_NOBLTHW = 7,
    DDSD_REPORT_NOCLIPLIST = 8,
    DDSD_REPORT_NODDROPSHW = 9,
    DDSD_REPORT_SURFACELOST = 10,
    DDSD_REPORT_UNSUPPORTED = 11,
    DDSD_REPORT_NOMIRRORHW = 12,
    DDSD_REPORT_NORASTEROPHW = 13,
    DDSD_REPORT_NOROTATIONHW = 14,
    DDSD_REPORT_NOSTRETCHHW = 15,
    DDSD_REPORT_SURFACEBUSY = 16,
    DDSD_REPORT_NOZBUFFERHW = 17,
    DDSD_REPORT_OUTOFMEMORY = 18,
    DDSD_REPORT_CLIPPERISUSINGHWND = 19,
    DDSD_REPORT_NOEXCLUSIVEMODE = 20,
    DDSD_REPORT_NOT8BITCOLOR = 21,
    DDSD_REPORT_NOPALETTEATTACHED = 22,
    DDSD_REPORT_NOPALETTEHW = 23,
    DDSD_REPORT_LOCKEDSURFACES = 24,
    DDSD_REPORT_IMPLICITLYCREATED = 25,
    DDSD_REPORT_WRONGMODE = 26,
    DDSD_REPORT_INCOMPATIBLEPRIMARY = 27,
    DDSD_REPORT_NOCLIPPERATTACHED = 28,
    DDSD_REPORT_UNKNOWN = 100
};

extern i32 gGraphicsType;
extern i32 gMainVideoModeHeight;
extern i32 gMainVideoModeWidth;
extern i32 gMainVideoModeColorDepth;
extern b32 gDDrawAttached;
extern b32 gWinGAttached;
extern b32 gWinGraphBusy;
extern void* gInitWin;
extern i32 gTtlBlts;

void SetFullScreenStatus(i32 fullScreen);
void InitGraphics();
void InitializePalette();
void UpdatePalette(i8* paletteData);
void CleanUpWinGraphics();
void RestoreDisplayMode();
i32 QueryNewPalette();
i32 SetGraphicsType(i32 graphicsType);
void GetGraphicsInfo(void);

#endif
