#ifndef HOMM1_BASE_SOUNDMGR_H
#define HOMM1_BASE_SOUNDMGR_H

enum ConfigVolumeLevel {
    SOUND_VOLUME_OFF = 0,
    SOUND_VOLUME_100 = 1,
    SOUND_VOLUME_90 = 2,
    SOUND_VOLUME_80 = 3,
    SOUND_VOLUME_70 = 4,
    SOUND_VOLUME_60 = 5,
    SOUND_VOLUME_50 = 6,
    SOUND_VOLUME_40 = 7,
    SOUND_VOLUME_30 = 8,
    SOUND_VOLUME_20 = 9,
    SOUND_VOLUME_10 = 10,
    SOUND_VOLUME_FIRST = SOUND_VOLUME_100,
    SOUND_VOLUME_LAST = SOUND_VOLUME_10
};

#endif
